version: '3'
services:
  todotests:
    depends_on:
      - todofront
      - todoback
    image: todotests
    environment:
      - FRONT_HOST=todofront
  todofront:
    depends_on:
      - todoback
    image: todofrontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    image: todobackend
    ports:
      - '3001:3001'