jobs:
  dockerfile-linter:
    runs-on: self-hosted
    name: Dockerfile Linter
    steps:
    - uses: actions/checkout@v2
    - name: Run Dockerfile Linter on Back-end
      run: docker run --rm -i hadolint/hadolint < ./docker/todo-app/back-end/Dockerfile
    - name: Run Dockerfile Linter on Front-end
      run: docker run --rm -i hadolint/hadolint < ./docker/todo-app/front-end/Dockerfile
    - name: Run Dockerfile Linter on Tests
      run: docker run --rm -i hadolint/hadolint < ./docker/todo-app/tests/Dockerfile
